/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

/**
 *
 * @author hasun
 */
public class MailTemplate {

    public static String registrationVerificationEmail(int code) {

        String email = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" lang=\"en\">\n"
                + "<head>\n"
                + "<title></title>\n"
                + "<meta charset=\"UTF-8\" />\n"
                + "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                + "<!--[if !mso]>-->\n"
                + "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n"
                + "<!--<![endif]-->\n"
                + "<meta name=\"x-apple-disable-message-reformatting\" content=\"\" />\n"
                + "<meta content=\"target-densitydpi=device-dpi\" name=\"viewport\" />\n"
                + "<meta content=\"true\" name=\"HandheldFriendly\" />\n"
                + "<meta content=\"width=device-width\" name=\"viewport\" />\n"
                + "<meta name=\"format-detection\" content=\"telephone=no, date=no, address=no, email=no, url=no\" />\n"
                + "<style type=\"text/css\">\n"
                + "table {\n"
                + "border-collapse: separate;\n"
                + "table-layout: fixed;\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt\n"
                + "}\n"
                + "table td {\n"
                + "border-collapse: collapse\n"
                + "}\n"
                + ".ExternalClass {\n"
                + "width: 100%\n"
                + "}\n"
                + ".ExternalClass,\n"
                + ".ExternalClass p,\n"
                + ".ExternalClass span,\n"
                + ".ExternalClass font,\n"
                + ".ExternalClass td,\n"
                + ".ExternalClass div {\n"
                + "line-height: 100%\n"
                + "}\n"
                + "body, a, li, p, h1, h2, h3 {\n"
                + "-ms-text-size-adjust: 100%;\n"
                + "-webkit-text-size-adjust: 100%;\n"
                + "}\n"
                + "html {\n"
                + "-webkit-text-size-adjust: none !important\n"
                + "}\n"
                + "body, #innerTable {\n"
                + "-webkit-font-smoothing: antialiased;\n"
                + "-moz-osx-font-smoothing: grayscale\n"
                + "}\n"
                + "#innerTable img+div {\n"
                + "display: none;\n"
                + "display: none !important\n"
                + "}\n"
                + "img {\n"
                + "Margin: 0;\n"
                + "padding: 0;\n"
                + "-ms-interpolation-mode: bicubic\n"
                + "}\n"
                + "h1, h2, h3, p, a {\n"
                + "line-height: inherit;\n"
                + "overflow-wrap: normal;\n"
                + "white-space: normal;\n"
                + "word-break: break-word\n"
                + "}\n"
                + "a {\n"
                + "text-decoration: none\n"
                + "}\n"
                + "h1, h2, h3, p {\n"
                + "min-width: 100%!important;\n"
                + "width: 100%!important;\n"
                + "max-width: 100%!important;\n"
                + "display: inline-block!important;\n"
                + "border: 0;\n"
                + "padding: 0;\n"
                + "margin: 0\n"
                + "}\n"
                + "a[x-apple-data-detectors] {\n"
                + "color: inherit !important;\n"
                + "text-decoration: none !important;\n"
                + "font-size: inherit !important;\n"
                + "font-family: inherit !important;\n"
                + "font-weight: inherit !important;\n"
                + "line-height: inherit !important\n"
                + "}\n"
                + "u + #body a {\n"
                + "color: inherit;\n"
                + "text-decoration: none;\n"
                + "font-size: inherit;\n"
                + "font-family: inherit;\n"
                + "font-weight: inherit;\n"
                + "line-height: inherit;\n"
                + "}\n"
                + "a[href^=\"mailto\"],\n"
                + "a[href^=\"tel\"],\n"
                + "a[href^=\"sms\"] {\n"
                + "color: inherit;\n"
                + "text-decoration: none\n"
                + "}\n"
                + "img,p{margin:0;Margin:0;font-family:Fira Sans,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:21px;font-weight:400;font-style:normal;font-size:14px;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#555;text-align:center;mso-line-height-rule:exactly;mso-text-raise:2px}h1{margin:0;Margin:0;font-family:Roboto,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:34px;font-weight:400;font-style:normal;font-size:28px;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#333;text-align:left;mso-line-height-rule:exactly;mso-text-raise:2px}h2{margin:0;Margin:0;font-family:Lato,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:30px;font-weight:400;font-style:normal;font-size:24px;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#333;text-align:left;mso-line-height-rule:exactly;mso-text-raise:2px}h3{margin:0;Margin:0;font-family:Lato,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:26px;font-weight:400;font-style:normal;font-size:20px;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#333;text-align:left;mso-line-height-rule:exactly;mso-text-raise:2px}\n"
                + "</style>\n"
                + "<style type=\"text/css\">\n"
                + "@media (min-width: 481px) {\n"
                + ".hd { display: none!important }\n"
                + "}\n"
                + "</style>\n"
                + "<style type=\"text/css\">\n"
                + "@media (max-width: 480px) {\n"
                + ".hm { display: none!important }\n"
                + "}\n"
                + "</style>\n"
                + "<style type=\"text/css\">\n"
                + "@media (min-width: 481px) {\n"
                + "h1,img,p{margin:0;Margin:0}.t11,.t15,.t19,.t26,.t28{width:280px!important}img,p{font-family:Fira Sans,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:21px;font-weight:400;font-style:normal;font-size:14px;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#555;text-align:center;mso-line-height-rule:exactly;mso-text-raise:2px}h1{font-family:Roboto,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:34px;font-weight:400;font-style:normal;font-size:28px;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#333;text-align:left;mso-line-height-rule:exactly;mso-text-raise:2px}h2,h3{margin:0;Margin:0;font-family:Lato,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;font-weight:400;font-style:normal;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#333;text-align:left;mso-line-height-rule:exactly;mso-text-raise:2px}h2{line-height:30px;font-size:24px}h3{line-height:26px;font-size:20px}.t28{padding:40px 60px 50px!important}.t34,.t38,.t40{width:400px!important}.t40{padding-left:0!important;padding-right:0!important}\n"
                + "}\n"
                + "</style>\n"
                + "<style type=\"text/css\">@media (min-width: 481px) {[class~=\"x_t28\"]{padding-left:60px!important;padding-top:40px!important;padding-bottom:50px!important;padding-right:60px!important;width:280px!important;} [class~=\"x_t15\"]{width:280px!important;} [class~=\"x_t11\"]{width:280px!important;} [class~=\"x_t26\"]{width:280px!important;} [class~=\"x_t40\"]{padding-left:0px!important;padding-right:0px!important;width:400px!important;} [class~=\"x_t38\"]{width:400px!important;} [class~=\"x_t34\"]{width:400px!important;} [class~=\"x_t19\"]{width:280px!important;}}</style>\n"
                + "<style type=\"text/css\" media=\"screen and (min-width:481px)\">.moz-text-html img,.moz-text-html p{margin:0;Margin:0;font-family:Fira Sans,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:21px;font-weight:400;font-style:normal;font-size:14px;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#555;text-align:center;mso-line-height-rule:exactly;mso-text-raise:2px}.moz-text-html h1{margin:0;Margin:0;font-family:Roboto,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:34px;font-weight:400;font-style:normal;font-size:28px;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#333;text-align:left;mso-line-height-rule:exactly;mso-text-raise:2px}.moz-text-html h2{margin:0;Margin:0;font-family:Lato,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:30px;font-weight:400;font-style:normal;font-size:24px;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#333;text-align:left;mso-line-height-rule:exactly;mso-text-raise:2px}.moz-text-html h3{margin:0;Margin:0;font-family:Lato,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:26px;font-weight:400;font-style:normal;font-size:20px;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#333;text-align:left;mso-line-height-rule:exactly;mso-text-raise:2px}.moz-text-html .t28{padding:40px 60px 50px!important;width:280px!important}.moz-text-html .t11,.moz-text-html .t15,.moz-text-html .t26{width:280px!important}.moz-text-html .t40{padding-left:0!important;padding-right:0!important;width:400px!important}.moz-text-html .t34,.moz-text-html .t38{width:400px!important}.moz-text-html .t19{width:280px!important}</style>\n"
                + "<!--[if !mso]>-->\n"
                + "<link href=\"https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;700&amp;family=Albert+Sans:wght@800&amp;display=swap\" rel=\"stylesheet\" type=\"text/css\" />\n"
                + "<!--<![endif]-->\n"
                + "<!--[if mso]>\n"
                + "<style type=\"text/css\">\n"
                + "img,p{margin:0;Margin:0;font-family:Fira Sans,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:21px;font-weight:400;font-style:normal;font-size:14px;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#555;text-align:center;mso-line-height-rule:exactly;mso-text-raise:2px}h1{margin:0;Margin:0;font-family:Roboto,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:34px;font-weight:400;font-style:normal;font-size:28px;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#333;text-align:left;mso-line-height-rule:exactly;mso-text-raise:2px}h2{margin:0;Margin:0;font-family:Lato,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:30px;font-weight:400;font-style:normal;font-size:24px;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#333;text-align:left;mso-line-height-rule:exactly;mso-text-raise:2px}h3{margin:0;Margin:0;font-family:Lato,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:26px;font-weight:400;font-style:normal;font-size:20px;text-decoration:none;text-transform:none;letter-spacing:0;direction:ltr;color:#333;text-align:left;mso-line-height-rule:exactly;mso-text-raise:2px}td.t28{padding:40px 60px 50px !important}td.t40{padding-left:0 !important;padding-right:0 !important}\n"
                + "</style>\n"
                + "<![endif]-->\n"
                + "<!--[if mso]>\n"
                + "<xml>\n"
                + "<o:OfficeDocumentSettings>\n"
                + "<o:AllowPNG/>\n"
                + "<o:PixelsPerInch>96</o:PixelsPerInch>\n"
                + "</o:OfficeDocumentSettings>\n"
                + "</xml>\n"
                + "<![endif]-->\n"
                + "</head>\n"
                + "<body id=body class=t45 style=\"min-width:100%;Margin:0px;padding:0px;background-color:#000000;\"><div class=t44 style=\"background-color:#000000;\"><table role=presentation width=100% cellpadding=0 cellspacing=0 border=0 align=center><tr><td class=t43 style=\"font-size:0;line-height:0;mso-line-height-rule:exactly;background-color:#000000;\" valign=top align=center>\n"
                + "<!--[if mso]>\n"
                + "<v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"true\" stroke=\"false\">\n"
                + "<v:fill color=#000000/>\n"
                + "</v:background>\n"
                + "<![endif]-->\n"
                + "<table role=presentation width=100% cellpadding=0 cellspacing=0 border=0 align=center id=innerTable><tr><td align=center>\n"
                + "<table class=t4 role=presentation cellpadding=0 cellspacing=0 style=\"Margin-left:auto;Margin-right:auto;\">\n"
                + "<tr>\n"
                + "<!--[if mso]>\n"
                + "<td width=400 class=t3 style=\"padding:40px 40px 40px 40px;\">\n"
                + "<![endif]-->\n"
                + "<!--[if !mso]>-->\n"
                + "<td class=t3 style=\"width:320px;padding:40px 40px 40px 40px;\">\n"
                + "<!--<![endif]-->\n"
                + "<table role=presentation width=100% cellpadding=0 cellspacing=0 style=\"width:100%!important;\"><tr><td align=center>\n"
                + "<table class=t2 role=presentation cellpadding=0 cellspacing=0 style=\"Margin-left:auto;Margin-right:auto;\">\n"
                + "<tr>\n"
                + "<!--[if mso]>\n"
                + "<td width=55 class=t1>\n"
                + "<![endif]-->\n"
                + "<!--[if !mso]>-->\n"
                + "<td class=t1 style=\"width:55px;\">\n"
                + "<!--<![endif]-->\n"
                + "<div style=\"font-size:0px;\"><img class=t0 style=\"display:block;border:0;height:auto;width:100%;Margin:0;max-width:100%;\" width=55 height=36.4375 alt=\"\" src=\"https://562ac5b4-0c3e-4075-94f8-60b6de4eb2f4.b-cdn.net/e/f44e698e-8725-4924-a37f-90300cd6a4e6/bcbf56b1-d4b3-40c7-b9e6-62b300784945.png\"/></div></td>\n"
                + "</tr></table>\n"
                + "</td></tr></table></td>\n"
                + "</tr></table>\n"
                + "</td></tr><tr><td align=center>\n"
                + "<table class=t31 role=presentation cellpadding=0 cellspacing=0 style=\"Margin-left:auto;Margin-right:auto;\">\n"
                + "<tr>\n"
                + "<!--[if mso]>\n"
                + "<td width=400 class=t30 style=\"background-color:#FFFFFF;\">\n"
                + "<![endif]-->\n"
                + "<!--[if !mso]>-->\n"
                + "<td class=t30 style=\"background-color:#FFFFFF;width:400px;\">\n"
                + "<!--<![endif]-->\n"
                + "<table role=presentation width=100% cellpadding=0 cellspacing=0 style=\"width:100%!important;\"><tr><td align=center>\n"
                + "<table class=t9 role=presentation cellpadding=0 cellspacing=0 style=\"Margin-left:auto;Margin-right:auto;\">\n"
                + "<tr>\n"
                + "<!--[if mso]>\n"
                + "<td width=400 class=t8 style=\"background-color:#CC9966;padding:40px 40px 40px 40px;\">\n"
                + "<![endif]-->\n"
                + "<!--[if !mso]>-->\n"
                + "<td class=t8 style=\"background-color:#CC9966;width:320px;padding:40px 40px 40px 40px;\">\n"
                + "<!--<![endif]-->\n"
                + "<table role=presentation width=100% cellpadding=0 cellspacing=0 style=\"width:100%!important;\"><tr><td align=center>\n"
                + "<table class=t7 role=presentation cellpadding=0 cellspacing=0 style=\"Margin-left:auto;Margin-right:auto;\">\n"
                + "<tr>\n"
                + "<!--[if mso]>\n"
                + "<td width=200 class=t6>\n"
                + "<![endif]-->\n"
                + "<!--[if !mso]>-->\n"
                + "<td class=t6 style=\"width:200px;\">\n"
                + "<!--<![endif]-->\n"
                + "<div style=\"font-size:0px;\"><img class=t5 style=\"display:block;border:0;height:auto;width:100%;Margin:0;max-width:100%;\" width=200 height=200 alt=\"\" src=\"https://562ac5b4-0c3e-4075-94f8-60b6de4eb2f4.b-cdn.net/e/f44e698e-8725-4924-a37f-90300cd6a4e6/681e4ced-7d01-4d3f-8015-78be40cc64b7.png\"/></div></td>\n"
                + "</tr></table>\n"
                + "</td></tr></table></td>\n"
                + "</tr></table>\n"
                + "</td></tr><tr><td align=center>\n"
                + "<table class=t29 role=presentation cellpadding=0 cellspacing=0 style=\"Margin-left:auto;Margin-right:auto;\">\n"
                + "<tr>\n"
                + "<!--[if mso]>\n"
                + "<td width=400 class=t28 style=\"padding:30px 30px 40px 30px;\">\n"
                + "<![endif]-->\n"
                + "<!--[if !mso]>-->\n"
                + "<td class=t28 style=\"width:340px;padding:30px 30px 40px 30px;\">\n"
                + "<!--<![endif]-->\n"
                + "<table role=presentation width=100% cellpadding=0 cellspacing=0 style=\"width:100%!important;\"><tr><td align=center>\n"
                + "<table class=t12 role=presentation cellpadding=0 cellspacing=0 style=\"Margin-left:auto;Margin-right:auto;\">\n"
                + "<tr>\n"
                + "<!--[if mso]>\n"
                + "<td width=280 class=t11>\n"
                + "<![endif]-->\n"
                + "<!--[if !mso]>-->\n"
                + "<td class=t11 style=\"width:340px;\">\n"
                + "<!--<![endif]-->\n"
                + "<h1 class=t10 style=\"margin:0;Margin:0;font-family:Albert Sans,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:35px;font-weight:800;font-style:normal;font-size:30px;text-decoration:none;text-transform:none;letter-spacing:-1.2px;direction:ltr;color:#333333;text-align:center;mso-line-height-rule:exactly;mso-text-raise:2px;\">Thank you for your registration</h1></td>\n"
                + "</tr></table>\n"
                + "</td></tr><tr><td><div class=t13 style=\"mso-line-height-rule:exactly;mso-line-height-alt:16px;line-height:16px;font-size:1px;display:block;\">&nbsp;&nbsp;</div></td></tr><tr><td align=left>\n"
                + "<table class=t16 role=presentation cellpadding=0 cellspacing=0 style=\"Margin-right:auto;\">\n"
                + "<tr>\n"
                + "<!--[if mso]>\n"
                + "<td width=280 class=t15>\n"
                + "<![endif]-->\n"
                + "<!--[if !mso]>-->\n"
                + "<td class=t15 style=\"width:340px;\">\n"
                + "<!--<![endif]-->\n"
                + "<p class=t14 style=\"margin:0;Margin:0;font-family:Inter Tight,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:21px;font-weight:400;font-style:normal;font-size:14px;text-decoration:none;text-transform:none;direction:ltr;color:#555555;text-align:center;mso-line-height-rule:exactly;mso-text-raise:2px;\">Please use below Verification Code to Verify your Molla Account.&nbsp;&nbsp;</p></td>\n"
                + "</tr></table>\n"
                + "</td></tr><tr><td><div class=t17 style=\"mso-line-height-rule:exactly;mso-line-height-alt:16px;line-height:16px;font-size:1px;display:block;\">&nbsp;&nbsp;</div></td></tr><tr><td align=center>\n"
                + "<table class=t20 role=presentation cellpadding=0 cellspacing=0 style=\"Margin-left:auto;Margin-right:auto;\">\n"
                + "<tr>\n"
                + "<!--[if mso]>\n"
                + "<td width=280 class=t19>\n"
                + "<![endif]-->\n"
                + "<!--[if !mso]>-->\n"
                + "<td class=t19 style=\"width:340px;\">\n"
                + "<!--<![endif]-->\n"
                + "<h1 class=t18 style=\"margin:0;Margin:0;font-family:Albert Sans,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:35px;font-weight:800;font-style:normal;font-size:30px;text-decoration:none;text-transform:none;letter-spacing:-1.2px;direction:ltr;color:#333333;text-align:center;mso-line-height-rule:exactly;mso-text-raise:2px;\">"+code+"</h1></td>\n"
                + "</tr></table>\n"
                + "</td></tr><tr><td><div class=t21 style=\"mso-line-height-rule:exactly;mso-line-height-alt:16px;line-height:16px;font-size:1px;display:block;\">&nbsp;&nbsp;</div></td></tr><tr><td><div class=t25 style=\"mso-line-height-rule:exactly;mso-line-height-alt:12px;line-height:12px;font-size:1px;display:block;\">&nbsp;&nbsp;</div></td></tr><tr><td align=center>\n"
                + "<table class=t27 role=presentation cellpadding=0 cellspacing=0 style=\"Margin-left:auto;Margin-right:auto;\">\n"
                + "<tr>\n"
                + "<!--[if mso]>\n"
                + "<td width=280 class=t26>\n"
                + "<![endif]-->\n"
                + "<!--[if !mso]>-->\n"
                + "<td class=t26 style=\"width:340px;\">\n"
                + "<!--<![endif]-->\n"
                + "<p class=t24 style=\"margin:0;Margin:0;font-family:Inter Tight,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:21px;font-weight:400;font-style:normal;font-size:14px;text-decoration:none;text-transform:none;direction:ltr;color:#555555;text-align:center;mso-line-height-rule:exactly;mso-text-raise:2px;\">or <a class=t23 href=\"\" style=\"margin:0;Margin:0;font-weight:700;font-style:normal;text-decoration:none;direction:ltr;color:#000000;mso-line-height-rule:exactly;\" target=_blank><span class=t22 style=\"margin:0;Margin:0;color:#CC9966;mso-line-height-rule:exactly;\">log in</span></a> to your account</p></td>\n"
                + "</tr></table>\n"
                + "</td></tr></table></td>\n"
                + "</tr></table>\n"
                + "</td></tr></table></td>\n"
                + "</tr></table>\n"
                + "</td></tr><tr><td><div class=t32 style=\"mso-line-height-rule:exactly;mso-line-height-alt:30px;line-height:30px;font-size:1px;display:block;\">&nbsp;&nbsp;</div></td></tr><tr><td align=center>\n"
                + "<table class=t41 role=presentation cellpadding=0 cellspacing=0 style=\"Margin-left:auto;Margin-right:auto;\">\n"
                + "<tr>\n"
                + "<!--[if mso]>\n"
                + "<td width=400 class=t40 style=\"padding:0 40px 0 40px;\">\n"
                + "<![endif]-->\n"
                + "<!--[if !mso]>-->\n"
                + "<td class=t40 style=\"width:320px;padding:0 40px 0 40px;\">\n"
                + "<!--<![endif]-->\n"
                + "<table role=presentation width=100% cellpadding=0 cellspacing=0 style=\"width:100%!important;\"><tr><td align=center>\n"
                + "<table class=t35 role=presentation cellpadding=0 cellspacing=0 style=\"Margin-left:auto;Margin-right:auto;\">\n"
                + "<tr>\n"
                + "<!--[if mso]>\n"
                + "<td width=400 class=t34>\n"
                + "<![endif]-->\n"
                + "<!--[if !mso]>-->\n"
                + "<td class=t34 style=\"width:320px;\">\n"
                + "<!--<![endif]-->\n"
                + "<p class=t33 style=\"margin:0;Margin:0;font-family:Inter Tight,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:18px;font-weight:400;font-style:normal;font-size:12px;text-decoration:none;text-transform:none;direction:ltr;color:#555555;text-align:center;mso-line-height-rule:exactly;mso-text-raise:2px;\">Molla is the country&#39;s largest and most renowned online furniture store, offering an extensive selection of high-quality furniture and home decor items.&nbsp;</p></td>\n"
                + "</tr></table>\n"
                + "</td></tr><tr><td><div class=t37 style=\"mso-line-height-rule:exactly;mso-line-height-alt:8px;line-height:8px;font-size:1px;display:block;\">&nbsp;&nbsp;</div></td></tr><tr><td align=center>\n"
                + "<table class=t39 role=presentation cellpadding=0 cellspacing=0 style=\"Margin-left:auto;Margin-right:auto;\">\n"
                + "<tr>\n"
                + "<!--[if mso]>\n"
                + "<td width=400 class=t38>\n"
                + "<![endif]-->\n"
                + "<!--[if !mso]>-->\n"
                + "<td class=t38 style=\"width:320px;\">\n"
                + "<!--<![endif]-->\n"
                + "<p class=t36 style=\"margin:0;Margin:0;font-family:Inter Tight,BlinkMacSystemFont,Segoe UI,Helvetica Neue,Arial,sans-serif;line-height:18px;font-weight:400;font-style:normal;font-size:12px;text-decoration:none;text-transform:none;direction:ltr;color:#555555;text-align:center;mso-line-height-rule:exactly;mso-text-raise:2px;\">Molla Inc. All rights reserved</p></td>\n"
                + "</tr></table>\n"
                + "</td></tr></table></td>\n"
                + "</tr></table>\n"
                + "</td></tr><tr><td><div class=t42 style=\"mso-line-height-rule:exactly;mso-line-height-alt:100px;line-height:100px;font-size:1px;display:block;\">&nbsp;&nbsp;</div></td></tr></table></td></tr></table></div></body>\n"
                + "</html>";

        return email;
    }

}
